{
 "title": "Airflow Monitor",
 "panels": [
  {
   "title": "Status Airflow",
   "type": "stat",
   "gridPos": { "h": 3, "w": 21, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select\n        -- Se último erro ocorreu com intervalo menor ou igual a 1 minuto, e em menos de 10 minutos\n        case when dif_last_error <= '00:01:00' and dif_now < '00:10:00' then\n        'Instável'\n        -- Se útimo erro ocorreu com intervalo superior a 1 minuto, e em menos de 30 minutos\n        when dif_last_error > '00:01:00' and dif_now < '00:30:00' then\n        'Atenção'\n        -- Se o percentual de erros estiver entre 5 a 10\n        when per_error between 5 and 10 then\n        'Atenção'\n        -- Se o percentual de erros for superior a 10 minutos\n        when per_error > 10 then\n        'Instável'\n        else\n        'Estável'\n        end as status_airflow\nfrom\n(\n    select\n        to_char(last_failed - before_last_failed, 'HH24:MI:SS')::time as dif_last_error,\n        to_char(current_timestamp - last_failed, 'HH24:MI:SS')::time as dif_now,\n        (qtd_error::float /\n        (\n            select\n                count(*)\n            from\n                dag_run dr3\n            where\n                    date(dr3.execution_date) = current_date\n        )::float) * 100 as per_error\n    from\n        (\n        select\n            (\n              select\n                      max(execution_date)\n              from\n                        dag_run dr2\n              where\n                      date(dr2.execution_date) = current_date and\n                      dr2.state = 'failed' and\n                      dr2.execution_date < max(dr1.execution_date)\n            ) as before_last_failed,\n            max(execution_date) as last_failed,\n            count(*) as qtd_error\n        from\n            dag_run dr1\n        where\n            date(execution_date) = current_date and\n            state = 'failed'\n    ) as errors\n) as gr"
    }
   ]
  },
  { "title": "Data Apache Airflow", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Import Errors",
   "type": "gauge",
   "description": "DAG Import Error",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        count(*) as qtd\nFROM\n        import_error"
    }
   ]
  },
  {
   "title": "Executions Today",
   "type": "stat",
   "gridPos": { "h": 8, "w": 10, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select\n        count(*) as total,\n        sum(case when state in ('success','running') then 1 else 0 end) as success,\n        sum(case when state = 'failed' then 1 else 0 end) as failed\n       -- sum(case when state = 'running' then 1 else 0 end) as running,\n       -- sum(case when state = 'queued' then 1 else 0 end) as queued\nfrom\n        dag_run\nwhere\n        date(execution_date) = current_date"
    }
   ]
  },
  {
   "title": "Dags Execution/Em Pausa",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 4, "x": 17, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        SUM(CASE WHEN is_paused = true THEN\n        1\n        ELSE\n        0\n        END) AS QTDPAUSE,\n        SUM(CASE WHEN is_paused = false THEN\n                     1\n                 ELSE\n                     0\n        END) AS QTDEXECUTION\nFROM\n        DAG"
    }
   ]
  },
  {
   "title": "Execution History",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select\n    to_char(data, 'yyyy-mm-dd HH24:MI')::timestamp as hora,\n    sum(success) as success,\n    sum(failed) as failed\n    --sum(running) as running,\n    --sum(queued) as queued\n\nfrom (select execution_date  as data,\n             case when state = 'success' then 1 else 0 end as success,\n             case when state = 'failed' then 1 else 0 end  as failed,\n             case when state = 'running' then 1 else 0 end as running,\n             case when state = 'queued' then 1 else 0 end  as queued\n      from dag_run\n      where execution_date >= current_timestamp - interval '24 hours'\n      order by data) as gr\ngroup by\n    to_char(data, 'yyyy-mm-dd HH24:MI')::timestamp\norder by\n    hora"
    }
   ]
  }
 ]
}